apiVersion: v1
kind: PersistentVolume
metadata:
  name: node-js-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/node-js
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: node-js-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
