apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-js-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-js
  template:
    metadata:
      labels:
        app: node-js
    spec:
      containers:
      - name: node-js-container
        image: <your-dockerhub-username>/node-js-sample:1.0
        ports:
        - containerPort: 5000
        volumeMounts:
        - mountPath: /usr/src/app/data
          name: node-js-volume
      volumes:
      - name: node-js-volume
        persistentVolumeClaim:
          claimName: node-js-pvc
